set MATLAB=C:\matlab\R2016a
"C:\matlab\R2016a\bin\win64\gmake" -f Crane3D_DevDriv.mk  EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 ISPROTECTINGMODEL=NOTPROTECTING OPTS="-DTGTCONN -DON_TARGET_WAIT_FOR_START=1"
